### ISSUE TITLE
Custom templates

### ISSUE THREAD

**Issue by eugenebolshakov** [heartcombo/mail_form#1]
Hi guys,

The README says that it's possible to specify your own custom template for the notifier, but I'm not sure how exactly that can be done given that the notifier's template_root is set to lib/../views and it seems to be trying to load templates from there. 

I guess it's possible to specify a relative path as a workaround if you have mail_form installed as a plugin, but in case of gem it won't work. 

I wonder if I'm missing something and if you guys use this feature yourself.

Thanks!

**Comment by acrolink** [comment]
I cannot locate this file: `config/initializers/mail_form.rb`.

Kindly explain how to customize the template in latest releases (where there is no `config/initializers/mail_form.rb` file).
