### ISSUE TITLE
Change date format?

### ISSUE THREAD

**Issue by sunef** [heartcombo/mail_form#52]
Hi and thanks for a great gem! Fantastic work.

I'm stuck on day 2 having problems changing the format of the date - **can you help me out so it doesn't output as 2017-19-02 but 02-19-2017?** - maybe it's really simple, but I've googled a lot with no luck and read the documentation

I have this in my contact.rb:
`  attribute :birthdaydate`
 
And in my view:
`<%= f.date_field :birthdaydate, value: 30.days.from_now.to_date.to_s, :as => :text %>`

I've tried putting this in my config/locales/en.yml:
```

en:
  date:
    formats:
      default: "%d/%m/%Y"
  time:
    formats:
      default: "%d/%m/%Y %H:%M"

```
But I can't seem to change the output. Any help would be greatly appreciated!

**Comment by nashby** [comment]
@sunef hey, did you try like this?

```
<%= f.date_field :birthdaydate, value: 30.days.from_now.strftime('%m-%d-%Y'), style: "height:39px; width:160px; font-size:14px; font-family: 'Lato', sans-serif;", :as => :text %>
```

**Comment by sunef** [comment]
Just tried like that. Unfortunately no luck.

Also tried :as => :date
`<%= f.date_field :bryllupsdato, style: "height:39px; width:160px; font-size:14px; font-family: 'Lato', sans-serif;", :as => :date %>`

and without :as => :text 
`<%= f.date_field :birthdaydate, value: 30.days.from_now.strftime('%m-%d-%Y'), style: "height:39px; width:160px; font-size:14px; font-family: 'Lato', sans-serif;" %>`

And without :as => :text but with strftime in value:
`<%= f.date_field :bryllupsdato, value: 30.days.from_now.strftime('%m-%d-%Y'), style: "height:39px; width:160px; font-size:14px; font-family: 'Lato', sans-serif;" %>`

It is as if either form_for's date_field converts whatever is picked as date into the format 2017-19-02 or mail_form somehow changes it to this format

Any other suggestions to get around this?

**Comment by sunef** [comment]
I guess what is happening is that somewhere there is run a default to_s method of Date

Also tried with this locale-approach from:
http://stackoverflow.com/questions/5102072/rails-how-to-control-how-date-field-is-rendered-in-a-form

in config/locales/en.yml: 
```
en:
  date:
    formats:
      slashes: "%d/%m/%Y"
```

and in view
`<%= f.date_field :bryllupsdato, value: 30.days.from_now.to_date.to_s, :format => :slashes %>`

**Comment by carlosantoniodasilva** [comment]
I'm closing this one as stale, and since it appears not to be related to MailForm specifically, but please do let us know if you're still having issues there, @sunef. Thanks.
