### ISSUE TITLE
Is this working for Rails 5.1?

### ISSUE THREAD

**Issue by adrianvalenz** [heartcombo/mail_form#57]
It's not working in production, so I'm not getting the email, plus I get a 500 server error. That Errno::EADDRNOTAVAIL and cannot access request email on port 25...

**Comment by adrianvalenz** [comment]
No one cares about this project anymore?

**Comment by rafaelfranca** [comment]
Our test are running with Rails 5.1 and they are all passing, so I'd say it is working with Rails 5.1. If you are having an issue please be more specific about which error you are getting and how to reproduce so we can help. Thanks

**Comment by aried3r** [comment]
We use this gem in production with Rails 5.1 and I'm currently working on adding support for 5.2 #60. I think the error is not related to this gem, but your email server config.
