### ISSUE TITLE
Email validation regular expression skips a lowercase underscore in domain name

### ISSUE THREAD

**Issue by krdprog** [heartcombo/mail_form#70]
An email validation regular expression skips addresses that have a lowercase underscore (_) in domain name.

`/\A([\w\.%\+\-]+)@([\w\-]+\.)+([\w]{2,})\z/i`

**Comment by carlosantoniodasilva** [comment]
Thanks for the report @krdprog. I actually simplified the example we have in the README with Devise's regexp, since that's not intended to be a full blown email validatior. Please see the commit message for more detail.
