### ISSUE TITLE
Net::SMTPAuthenticationError

### ISSUE THREAD

**Issue by carlos-ssh** [heartcombo/mail_form#75]
Hello guys I had my setup working well after a time I have this error:
```
Completed 500 Internal Server Error in 892ms (ActiveRecord: 0.0ms | Allocations: 19634)
Net::SMTPAuthenticationError (530-5.7.0 Authentication Required. Learn more at
):
```
Somebody can solve it?

**Comment by carlosantoniodasilva** [comment]
@carlos-ssh this is essentially an issue sending the email, so it's a configuration related to your SMTP settings.

You can test an email outside of MailForm (just a regular Rails mailer), and you should see the same error, which would confirm it's not related to MailForm and probably SMTP settings like I mentioned.

I'd also recommend checking this Rails guide: https://guides.rubyonrails.org/action_mailer_basics.html#action-mailer-configuration, and making sure your SMTP configs are working.
